services:
  chromium-test:
    build:
      context: .
      dockerfile: Dockerfile.chromium
    container_name: playwright_chromium
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    environment:
      MAVEN_OPTS: "-Xmx1024m"
    tty: true

  firefox-test:
    build:
      context: .
      dockerfile: Dockerfile.firefox
    container_name: playwright_firefox
    volumes:
      - .:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    environment:
      MAVEN_OPTS: "-Xmx1024m"
    tty: true
